In [117]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

# workig with api

```
url="api link{with api key}"
response=requests.get(url)
df=pd.Dataframe(response.json()[col])[col]
```
col=columns name

# working with web_scrap

In [118]:
from bs4 import BeautifulSoup
import requests

headers = {
    "User-Agent": "Mozilla/5.0"
}

web = requests.get(
    "https://www.ambitionbox.com/list-of-companies?page=1",
    headers=headers
)

soup = BeautifulSoup(web.text, "html.parser")

In [119]:
final=pd.DataFrame()
for j in range (1,11):
    url=f"https://www.ambitionbox.com/list-of-companies?page={j}"
    headers = {"User-Agent": "Mozilla/5.0"}
    web = requests.get( url,headers=headers)
    soup = BeautifulSoup(web.text, "html.parser")
    
    name=[]
    ratings=[]
    Type=[]
    review=[]
    salary=[]
    interview=[]
    job=[]
    benifits=[]
    photos=[]
    company=soup.find_all('div', class_='companyCardWrapper__primaryInformation')
    for i in company:
        name.append(i.find('h2').text.strip())
        ratings.append(i.find('div', class_="rating_star_container").text.strip())
        Type.append(i.find('span', class_="companyCardWrapper__interLinking").text.strip())
        
    company=soup.find_all('div', class_="companyCardWrapper__tertiaryInformation")
    for i in company:
        review.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[0].text.strip())
        salary.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[1].text.strip())
        interview.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[2].text.strip())
        job.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[3].text.strip())
        benifits.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[4].text.strip())
        photos.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[5].text.strip())
    d={
    'name':name,
    'ratings':ratings,
    'type|location':Type,
    'review':review,
    'salary':salary,
    'interview':interview,
    'job':job,
    'benfits':benifits,
    'photos':photos
    }
    df=pd.DataFrame(d)

    final=pd.concat([final,df],ignore_index=True)

In [120]:
final.head()

,name,ratings,type|location,review,salary,interview,job,benfits,photos
0,TCS,3.3,IT Services & Consulting | Bengaluru +439 othe...,1.1L,9.9L,11.9k,3.3k,10.6k,93
1,Accenture,3.7,IT Services & Consulting | Bengaluru +255 othe...,72.1k,6.5L,9.2k,36.3k,6.7k,49
2,Wipro,3.6,IT Services & Consulting | Hyderabad +371 othe...,64.1k,4.8L,6.7k,4.7k,4.6k,107
3,Cognizant,3.6,IT Services & Consulting | Hyderabad +232 othe...,60.4k,6L,6.4k,550,5.5k,86
4,Capgemini,3.7,IT Services & Consulting | Bengaluru +182 othe...,52.1k,4.8L,5.5k,2.8k,3.7k,42

In [121]:
final.count()

name             200
ratings          200
type|location    200
review           200
salary           200
interview        200
job              200
benfits          200
photos           200
dtype: int64

In [122]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           200 non-null    object
 1   ratings        200 non-null    object
 2   type|location  200 non-null    object
 3   review         200 non-null    object
 4   salary         200 non-null    object
 5   interview      200 non-null    object
 6   job            200 non-null    object
 7   benfits        200 non-null    object
 8   photos         200 non-null    object
dtypes: object(9)
memory usage: 14.2+ KB

In [132]:
final=final.replace('--',np.nan)
cols = ["review","salary","interview","job","benfits"]

final[cols] = final[cols].replace({'L':'e5','k':'e3'}, regex=True).astype(float)

final= final.astype({
    "ratings": "float"
})
final["photos"] = final["photos"].fillna(0).astype(int)

In [133]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           200 non-null    object
 1   ratings        200 non-null    float64
 2   type|location  200 non-null    object
 3   review         200 non-null    float64
 4   salary         200 non-null    float64
 5   interview      200 non-null    float64
 6   job            183 non-null    float64
 7   benfits        200 non-null    float64
 8   photos         200 non-null    int64
dtypes: float64(6), int64(1), object(2)
memory usage: 14.2+ KB

In [134]:
final.head()

,name,ratings,type|location,review,salary,interview,job,benfits,photos
0,TCS,3.3,IT Services & Consulting | Bengaluru +439 othe...,110000.0,990000.0,11900.0,3300.0,10600.0,93
1,Accenture,3.7,IT Services & Consulting | Bengaluru +255 othe...,72100.0,650000.0,9200.0,36300.0,6700.0,49
2,Wipro,3.6,IT Services & Consulting | Hyderabad +371 othe...,64100.0,480000.0,6700.0,4700.0,4600.0,107
3,Cognizant,3.6,IT Services & Consulting | Hyderabad +232 othe...,60400.0,600000.0,6400.0,550.0,5500.0,86
4,Capgemini,3.7,IT Services & Consulting | Bengaluru +182 othe...,52100.0,480000.0,5500.0,2800.0,3700.0,42

In [135]:
final['salary'].dtype

dtype('float64')